[project]
name = "clipboard-revamped"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "keyboard>=0.13.5",
    "pyqt6>=6.10.0",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.17.0",
]
